name: Trigger docs update

on:
  push:
    branches:
      - 'rc'
      - 'release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: "actions:write"

      - name: Trigger docs update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release.yml
          ref: main
          repo: altmp/altv-docs-new
          token: ${{ steps.get_workflow_token.outputs.token }}